services:
  cups-pdf:
    image: mjmaisey/pdf-printer-docker:latest
    container_name: pdf-printer
    ports:
      - "631:631"
    environment:
      - PRINTER_NAME=PDF-Printer
    volumes:
      - ./pdfs:/pdfs
    restart: unless-stopped
